In [23]:
import pandas as pd
import requests

In [24]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [ ]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [26]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,143.3652,9.273,821
1,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,25.0413,8.900,347
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,59.0684,8.886,2096
3,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,58.1371,8.727,31005
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,126.2866,8.699,1799

In [27]:
df = pd.DataFrame()

In [28]:
df

Empty DataFrame
Columns: []
Index: []

In [30]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [32]:
df.to_csv('movies.csv')