In [1]:
import pandas as pd

# Working with JSON

1.Imported kagglehub

In [4]:
!pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.2-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.22 (from kagglehub)
  Downloading kagglesdk-0.1.37-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in d:\anaconda\lib\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in d:\anaconda\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in d:\anaconda\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in d:\anaconda\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in d:\anaconda\lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.3)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\anaconda\lib\site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda\lib\site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests->kagglehub) (2026.7.22)
Requirement already satisfied: colorama in d:\anaconda\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.2-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.37-py3-none-any.whl (262 kB)
Installing collected packages: kagglesdk, kagglehub

   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   -------------------- ------------------- 1/2 [kagglehub]
   -------------------- ------------------- 1/2 [kagglehub]
   -------------------- ------------------- 1/2 [kagglehub]
   -------------------- ------------------- 1/2 [kagglehub]
   -------------------- ------------------- 1/2 [kagglehub]
   -------------------- ------------------- 1/2 [kagglehub]
   ---------------------------------------- 2/2 [kagglehub]

Successfully installed kagglehub-1.0.2 kagglesdk-0.1.37

2. downloaded kagle file

In [5]:
import kagglehub

path = kagglehub.dataset_download("kaggle/recipe-ingredients-dataset")

print("Path to dataset files:", path)

Downloading to C:\Users\Naitik\.cache\kagglehub\datasets\kaggle\recipe-ingredients-dataset\1.archive...

100%|██████████| 2.23M/2.23M [00:06<00:00, 363kB/s]

Extracting files...
Path to dataset files: C:\Users\Naitik\.cache\kagglehub\datasets\kaggle\recipe-ingredients-dataset\versions\1

In [8]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [9]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-13,1786579201,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-13,1786579201,0.0385
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-13,1786579201,0.6840
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-13,1786579201,0.8450
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-13,1786579201,3.8400
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-13,1786579201,2.4900
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-13,1786579201,0.1690
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-13,1786579201,0.1970
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-13,1786579201,0.2790
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-13,1786579201,0.2790

# Working with SQL

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("busielmorley/worldcities-pop-lang-rank-sql-create-tbls")

print("Path to dataset files:", path)

Downloading to C:\Users\Naitik\.cache\kagglehub\datasets\busielmorley\worldcities-pop-lang-rank-sql-create-tbls\1.archive...

100%|██████████| 89.9k/89.9k [00:00<00:00, 327kB/s]

Extracting files...
Path to dataset files: C:\Users\Naitik\.cache\kagglehub\datasets\busielmorley\worldcities-pop-lang-rank-sql-create-tbls\versions\1